---
# tasks file for ExampleRole
- name: Install Apache
  yum:
    name: "{{ yum_package }}"
    state: latest
  register: result
- debug:
    var=result
    
- name: Install Nginx
  yum:
    name: httpd
    state: latest
  when: result is true
  
